name: cellx
on: [push, pull_request]

jobs:
  lint_and_test:
    name: Run flake8 and pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10.9'
#     - uses: psf/black@stable
#       with:
#         options: "--check --verbose --line-length=79"
    - name:
        Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install pytest
    - name: Run Flake8
      run: |
        flake8
    - name: Test with pytest
      run: |
        pip install -e .
        pytest

